# Generated by Django 4.1.3 on 2022-11-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_options_alter_movieseries_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="img",
            field=models.ImageField(default="1", upload_to="", verbose_name="Сурет"),
            preserve_default=False,
        ),
    ]
