# Generated by Django 4.1.3 on 2022-11-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="max_series",
            field=models.IntegerField(default=12, verbose_name="Жалпы бөлім саны"),
        ),
    ]
