# Generated by Django 4.1.3 on 2022-11-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_movie_max_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="url",
            field=models.SlugField(default="1", max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
