# Generated by Django 4.1.3 on 2022-11-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_movie_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="img",
            field=models.ImageField(upload_to="anime/%y/%m/%d", verbose_name="Сурет"),
        ),
    ]
