# Generated by Django 4.1.3 on 2022-11-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_movie_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="continued",
            field=models.BooleanField(default=True, verbose_name="Жалғасуда"),
        ),
    ]
