# Generated by Django 4.1.3 on 2022-11-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_movie_continued"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="full_length",
            field=models.BooleanField(default=False, verbose_name="Фильм"),
        ),
    ]
