# Generated by Django 4.1.3 on 2022-11-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_moviecomments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moviecomments",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="moviecomments",
            name="likes",
        ),
    ]
