# Generated by Django 4.1.3 on 2022-11-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_alter_moviecomments_user_dislikes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moviecomments",
            name="movie",
        ),
        migrations.AddField(
            model_name="moviecomments",
            name="episode",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="movies.movieseries",
            ),
            preserve_default=False,
        ),
    ]
