# Generated by Django 4.1.3 on 2022-11-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0012_remove_moviecomments_movie_moviecomments_episode"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="landscape_photo",
            field=models.ImageField(
                default="landscape_photo.jpg",
                upload_to="anime/%y/%m/%d",
                verbose_name="Пейзаждық фото",
            ),
        ),
    ]
