# Generated by Django 4.1.3 on 2022-12-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0013_movie_landscape_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="banner",
            field=models.BooleanField(default=False),
        ),
    ]
