# Generated by Django 4.1.3 on 2022-12-07 17:57

import admin_async_upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0014_movie_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieseries",
            name="video_file",
            field=admin_async_upload.models.AsyncFileField(
                blank=True, null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(verbose_name="Сипаттама"),
        ),
        migrations.AlterField(
            model_name="movieseries",
            name="iframe_link",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="OK.ru LINK"
            ),
        ),
    ]
